name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - django-version: "2.2"
            python-version: "3.8"
          - django-version: "3.2"
            python-version: "3.9"
          - django-version: "4.2"
            python-version: "3.10"
          - django-version: "4.2"
            python-version: "3.11"
          - django-version: "5.1"
            python-version: "3.12"
          - django-version: "5.2"
            python-version: "3.13"

    name: Django ${{ matrix.django-version }} (Python ${{ matrix.python-version }})

    env:
      DJANGO: ${{ matrix.django-version }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -mpip install tox tox-gh-actions
    - name: Test with tox
      run: tox -- -vvv
